### ISSUE TITLE
option to disable docker-host network policy

### ISSUE THREAD

**Issue by shreddedbacon** [uselagoon/lagoon-charts#485]
Currently the network policy with docker-host is enforced. 

It would be nice to allow this to be disabled

**Comment by smlx** [comment]
This was intentional. The motivation was:
* avoid config bloat
* secure by default
* both the docker-host and network policy are part of the same chart and use the same templates for selector labels etc. So there shouldn't be any problem with keeping them in sync.

With https://github.com/uselagoon/build-deploy-tool/pull/119 fixing the issue with builds failing do you still want to be able to turn off the network policy?
