### ISSUE TITLE
lagoon-remote: reduce roles for lagoon-build-deploy serviceaccount?

### ISSUE THREAD

**Issue by smlx** [uselagoon/lagoon-charts#77]
There are currently a lot of wide and overlapping permissions that possibly could be tightened up.

**Comment by smlx** [comment]
@shreddedbacon is there any way these can be pruned down a bit, since they're all bound to the same serviceaccount?

* https://github.com/uselagoon/lagoon-charts/blob/main/charts/lagoon-remote/templates/lagoon-build-deploy.clusterrole.yaml
* https://github.com/uselagoon/lagoon-charts/blob/main/charts/lagoon-remote/templates/lagoon-build-deploy.role.yaml

**Comment by shreddedbacon** [comment]
The manager role probably won't be cluster-admin in production, it is only cluster-admin as I haven't finished scoping the role fully yet.

Kubebuilder uses kustomize instead of helm to generate the yaml, it is entirely possible that I've just done something wrong converting it into helm initially. Will review

**Comment by shreddedbacon** [comment]
@smlx I think it will be fine to reduce everything down to the `cluster-admin` role the same as `kubernetesBuildDeploy`.
